In [97]:
import pandas as pd
df = pd.read_excel('data/score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [2]:
def add_cm(height):
    if isinstance(height, int):
        return str(height) + 'cm'
    else:
        return int(height.replace('cm', ''))

df['키'] = df['키'].apply(add_cm)
df.head(5)

       이름   학교      키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197cm  90  85  100  95  85      Python
2번    정대만  북산고  184cm  40  35   50  55  25        Java
3번    송태섭  북산고  168cm  80  75   70  80  75  Javascript
4번    서태웅  북산고  187cm  40  60   70  75  80         NaN
5번    강백호  북산고  188cm  15  20   10  35  10         NaN

In [3]:
df['키'] = df['키'].apply(lambda x:str(x) + 'cm' if isinstance(x, int) else int(x.replace('cm', '')))
df.head(5)

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85      Python
2번    정대만  북산고  184  40  35   50  55  25        Java
3번    송태섭  북산고  168  80  75   70  80  75  Javascript
4번    서태웅  북산고  187  40  60   70  75  80         NaN
5번    강백호  북산고  188  15  20   10  35  10         NaN

In [4]:
def capitalize(lang):
    if pd.notnull(lang):
        return lang.capitalize()
    return lang

df['SW특기'] = df['SW특기'].apply(capitalize)
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      Python
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [5]:
def capitalize(lang):
    if pd.notnull(lang):
        return lang.capitalize()
    return lang

df['SW특기'] = df['SW특기'].apply(capitalize)
df.tail(4)

       이름   학교    키   국어   영어  수학  과학  사회    SW특기
지원번호
5번    강백호  북산고  188   15   20  10  35  10     NaN
6번    변덕규  능남고  202   80  100  95  85  80       C
7번    황태산  능남고  188   55   65  45  40  35  Python
8번    윤대협  능남고  190  100   85  90  95  95      C#

In [6]:
df['SW특기'] = df['SW특기'].apply(lambda x: x.capitalize() if pd.notna(x) else x)
df.tail(4)

       이름   학교    키   국어   영어  수학  과학  사회    SW특기
지원번호
5번    강백호  북산고  188   15   20  10  35  10     NaN
6번    변덕규  능남고  202   80  100  95  85  80       C
7번    황태산  능남고  188   55   65  45  40  35  Python
8번    윤대협  능남고  190  100   85  90  95  95      C#

In [7]:
df_score = df.loc[:, '국어':'사회']
df_score.head()

      국어  영어   수학  과학  사회
지원번호
1번    90  85  100  95  85
2번    40  35   50  55  25
3번    80  75   70  80  75
4번    40  60   70  75  80
5번    15  20   10  35  10

In [8]:
df_score['총점']=df_score.apply(lambda row:row['국어']+row['영어']+row['수학']+row['과학']+row['사회'], axis=1)
df_score

       국어   영어   수학  과학  사회   총점
지원번호
1번     90   85  100  95  85  455
2번     40   35   50  55  25  205
3번     80   75   70  80  75  380
4번     40   60   70  75  80  325
5번     15   20   10  35  10   90
6번     80  100   95  85  80  440
7번     55   65   45  40  35  240
8번    100   85   90  95  95  465

In [9]:
df_score['평균'] = df_score.apply(lambda row:row['총점']/5, axis=1)
df_score

       국어   영어   수학  과학  사회   총점    평균
지원번호
1번     90   85  100  95  85  455  91.0
2번     40   35   50  55  25  205  41.0
3번     80   75   70  80  75  380  76.0
4번     40   60   70  75  80  325  65.0
5번     15   20   10  35  10   90  18.0
6번     80  100   95  85  80  440  88.0
7번     55   65   45  40  35  240  48.0
8번    100   85   90  95  95  465  93.0

In [10]:
import numpy as np
df_score.loc['합계'] = df_score.apply(np.sum, axis=0)
df_score

         국어     영어     수학     과학     사회      총점     평균
지원번호
1번     90.0   85.0  100.0   95.0   85.0   455.0   91.0
2번     40.0   35.0   50.0   55.0   25.0   205.0   41.0
3번     80.0   75.0   70.0   80.0   75.0   380.0   76.0
4번     40.0   60.0   70.0   75.0   80.0   325.0   65.0
5번     15.0   20.0   10.0   35.0   10.0    90.0   18.0
6번     80.0  100.0   95.0   85.0   80.0   440.0   88.0
7번     55.0   65.0   45.0   40.0   35.0   240.0   48.0
8번    100.0   85.0   90.0   95.0   95.0   465.0   93.0
합계    500.0  525.0  530.0  560.0  485.0  2600.0  520.0

In [11]:
df.groupby('학교')[['키']].mean()

              키
학교
능남고  193.333333
북산고  184.800000

In [12]:
df.groupby('학교')[['국어', '영어', '수학']].mean()

            국어         영어         수학
학교
능남고  78.333333  83.333333  76.666667
북산고  53.000000  55.000000  60.000000

In [25]:
df.groupby('학교')[['국어', '영어', '수학']].sum()

      국어   영어   수학
학교
능남고  235  250  230
북산고  265  275  300

In [26]:
df.groupby('학교')[['국어', '영어', '수학']].count()

     국어  영어  수학
학교
능남고   3   3   3
북산고   5   5   5

In [13]:
df['학년'] = [3, 3, 3, 1, 1, 3, 2, 2]
df.head()

       이름   학교    키  국어  영어   수학  과학  사회        SW특기  학년
지원번호
1번    채치수  북산고  197  90  85  100  95  85      Python   3
2번    정대만  북산고  184  40  35   50  55  25        Java   3
3번    송태섭  북산고  168  80  75   70  80  75  Javascript   3
4번    서태웅  북산고  187  40  60   70  75  80         NaN   1
5번    강백호  북산고  188  15  20   10  35  10         NaN   1

In [14]:
df.groupby(['학교', '학년'])[['국어', '영어', '수학', '과학', '사회']].mean()

          국어     영어         수학         과학         사회
학교  학년
능남고 2   77.5   75.0  67.500000  67.500000  65.000000
    3   80.0  100.0  95.000000  85.000000  80.000000
북산고 1   27.5   40.0  40.000000  55.000000  45.000000
    3   70.0   65.0  73.333333  76.666667  61.666667

In [15]:
df.groupby('학년')[['키']].mean()

         키
학년
1   187.50
2   189.00
3   187.75

In [16]:
df.groupby('학년')[['키']].mean().sort_values('키', ascending=False)

         키
학년
2   189.00
3   187.75
1   187.50

In [17]:
df.groupby('학년')[['키']].mean().sort_index(ascending=False)

         키
학년
3   187.75
2   189.00
1   187.50

In [18]:
df.groupby('학년')[['국어', '영어']].mean().sort_values(['국어', '영어'], ascending=[True, False])

      국어     영어
학년
1   27.5  40.00
3   72.5  73.75
2   77.5  75.00

In [19]:
df.groupby(['학교', '학년'])[['키']].mean().sort_index(ascending=[True, False])

            키
학교  학년
능남고 3   202.0
    2   189.0
북산고 3   183.0
    1   187.5

In [20]:
df.groupby('학교')['이름'].count().to_frame('학생수')

     학생수
학교
능남고    3
북산고    5

In [21]:
df.groupby(['학교', '학년'])['이름'].count().to_frame('학생수')

        학생수
학교  학년
능남고 2     2
    3     1
북산고 1     2
    3     3

In [22]:
df.groupby('학교')['학년'].value_counts().to_frame('학생수')

        학생수
학교  학년
능남고 2     2
    3     1
북산고 3     3
    1     2

In [23]:
school = df['학교'].value_counts().to_frame('학생수')
school

     학생수
학교
북산고    5
능남고    3

In [29]:
df.head(3)

       이름   학교    키  국어  영어   수학  과학  사회        SW특기  학년
지원번호
1번    채치수  북산고  197  90  85  100  95  85      Python   3
2번    정대만  북산고  184  40  35   50  55  25        Java   3
3번    송태섭  북산고  168  80  75   70  80  75  Javascript   3

In [31]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기  학년
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python   3
2번    정대만  북산고  184   40   35   50  55  25        Java   3
3번    송태섭  북산고  168   80   75   70  80  75  Javascript   3
4번    서태웅  북산고  187   40   60   70  75  80         NaN   1
5번    강백호  북산고  188   15   20   10  35  10         NaN   1
6번    변덕규  능남고  202   80  100   95  85  80           C   3
7번    황태산  능남고  188   55   65   45  40  35      Python   2
8번    윤대협  능남고  190  100   85   90  95  95          C#   2

In [58]:
df.groupby('학교').size()

학교
능남고    3
북산고    5
dtype: int64

In [62]:
df.groupby('학교').count()[['이름','SW특기']]

     이름  SW특기
학교
능남고   3     3
북산고   5     3

In [65]:
df.groupby('학교')[['이름', 'SW특기']].count()

     이름  SW특기
학교
능남고   3     3
북산고   5     3

In [66]:
df['SW특기'].unique()

array(['Python', 'Java', 'Javascript', nan, 'C', 'C#'], dtype=object)

In [70]:
df['SW특기'].value_counts().to_frame('학생수')

            학생수
SW특기
Python        2
Java          1
Javascript    1
C             1
C#            1

In [68]:
df['SW특기'].value_counts()['Python']

np.int64(2)

In [71]:
df['SW특기'].value_counts(normalize=True).to_frame('비율')

                  비율
SW특기
Python      0.333333
Java        0.166667
Javascript  0.166667
C           0.166667
C#          0.166667

In [98]:
df.groupby('학교')['SW특기'].unique().to_frame('SW특기')

                                SW특기
학교
능남고                  [C, PYTHON, C#]
북산고  [Python, Java, Javascript, nan]

In [87]:
df.loc['4번', 'SW특기'] = 'Python'
df.loc['5번', 'SW특기'] = 'C#'
df.head(5)

       이름   학교    키  국어  영어   수학  과학  사회        SW특기  학년
지원번호
1번    채치수  북산고  197  90  85  100  95  85      Python   3
2번    정대만  북산고  184  40  35   50  55  25        Java   3
3번    송태섭  북산고  168  80  75   70  80  75  Javascript   3
4번    서태웅  북산고  187  40  60   70  75  80      Python   1
5번    강백호  북산고  188  15  20   10  35  10          C#   1

In [92]:
school=df.groupby('학교')['SW특기'].value_counts().to_frame('학생수')
school

                학생수
학교  SW특기
능남고 C             1
    C#            1
    Python        1
북산고 Python        2
    C#            1
    Java          1
    Javascript    1

In [96]:
school.loc['북산고','Python']

학생수    2
Name: (북산고, Python), dtype: int64