In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/score.csv', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [4]:
df.groupby('학교').get_group('능남고')

       이름   학교    키   국어   영어  수학  과학  사회    SW특기
지원번호
6번    변덕규  능남고  202   80  100  95  85  80       C
7번    황태산  능남고  188   55   65  45  40  35  PYTHON
8번    윤대협  능남고  190  100   85  90  95  95      C#

In [5]:
df.groupby('학교').get_group('북산고')

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85      Python
2번    정대만  북산고  184  40  35   50  55  25        Java
3번    송태섭  북산고  168  80  75   70  80  75  Javascript
4번    서태웅  북산고  187  40  60   70  75  80         NaN
5번    강백호  북산고  188  15  20   10  35  10         NaN

In [6]:
df.groupby('학교')['키'].mean()

학교
능남고    193.333333
북산고    184.800000
Name: 키, dtype: float64

In [7]:
df.groupby('학교')[['국어','영어', '수학']].mean()

            국어         영어         수학
학교
능남고  78.333333  83.333333  76.666667
북산고  53.000000  55.000000  60.000000

In [9]:
df['학년']=[3, 3, 3, 1, 1, 3, 2, 2]

In [10]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기  학년
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python   3
2번    정대만  북산고  184   40   35   50  55  25        Java   3
3번    송태섭  북산고  168   80   75   70  80  75  Javascript   3
4번    서태웅  북산고  187   40   60   70  75  80         NaN   1
5번    강백호  북산고  188   15   20   10  35  10         NaN   1
6번    변덕규  능남고  202   80  100   95  85  80           C   3
7번    황태산  능남고  188   55   65   45  40  35      PYTHON   2
8번    윤대협  능남고  190  100   85   90  95  95          C#   2

In [12]:
df.groupby(['학교', '학년'])[['키']].mean()

            키
학교  학년
능남고 2   189.0
    3   202.0
북산고 1   187.5
    3   183.0